openapi: 3.0.0
info:
  title: Todo Chatbot API
  version: 1.0.0
  description: API for the Todo Chatbot application deployed on Kubernetes

servers:
  - url: http://todo-chatbot-backend:8000
    description: Backend service in Kubernetes cluster

paths:
  /api/todos:
    get:
      summary: Get all todos for the authenticated user
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreate'
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

  /api/todos/{id}:
    get:
      summary: Get a specific todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Todo details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    put:
      summary: Update a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    delete:
      summary: Delete a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Todo deleted successfully

  /api/chat:
    post:
      summary: Chat with the todo bot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Chat response from the bot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - title
        - completed
        - createdAt
        - updatedAt

    TodoCreate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
      required:
        - title

    TodoUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean

    ChatRequest:
      type: object
      properties:
        message:
          type: string
        userId:
          type: string
      required:
        - message
        - userId

    ChatResponse:
      type: object
      properties:
        response:
          type: string
        todoAction:
          type: string
        todoData:
          type: object